server:
  port: 8099
spring:
  application:
    name: comsumer-hystrix-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    filters: stat
    max-active: 30
    initial-size: 1
    max-wait: 60000
    min-idle: 5
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 50
    max-pool-prepared-statement-per-connection-size: 20
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  hystrix:
    enabled: true # 开启feign熔断功能
logging:
  level:
    com:
      study:
        feign:
          dao: debug
hystrix:
  metrics:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream